"""Data models for kaggle-harvester.

Note: Models are now partitioned into `harvester.schemas.*`.
This module re-exports all models for 100% backwards compatibility.
"""

from __future__ import annotations

from .schemas import (
    COMPETITION_SLUG_PATTERN,
    DEFAULT_FALLBACK_COMPETITION,
    ActiveCompetitionInfo,
    ArchiveEntry,
    ArchiveRequest,
    ArchiveResult,
    ArchiverConfig,
    AutoArchiveCheckedItem,
    AutoArchiveConfig,
    AutoArchiveItemResult,
    AutoArchiveRunDetail,
    AutoArchiveRunLog,
    AutoArchiveSnapshot,
    AutoArchiveStatus,
    CompetitionInfo,
    CompetitionSubmission,
    EnrichRequest,
    EnteredCompetition,
    KernelListRequest,
    KernelSummary,
    NotificationChannelResult,
    NotificationConfig,
    NotificationConfigUpdate,
    NotificationConfigView,
    NotificationSnapshot,
    NotificationStatus,
    NotificationTestResult,
    ScoreDirection,
    ScoredKernel,
    SetActiveCompetitionRequest,
    SimulationAgentStats,
    SimulationClawbotStatus,
    SimulationClawbotTestCandidate,
    SimulationClawbotTestResult,
    SimulationEpisode,
    SimulationEpisodeAgent,
    SimulationEpisodePageResponse,
    SimulationHistoryPoint,
    SimulationMedalThresholds,
    SimulationMonitorConfig,
    SimulationMonitorRunDetail,
    SimulationMonitorRunLog,
    SimulationMonitorSnapshot,
    SimulationMonitorStatus,
    SimulationRatingPoint,
    SortBy,
    SubmissionMonitorConfig,
    SubmissionMonitorItem,
    SubmissionMonitorRunDetail,
    SubmissionMonitorRunLog,
    SubmissionMonitorSnapshot,
    SubmissionMonitorStatus,
    SubmissionScoreEvent,
    VersionInfo,
    VersionScoreList,
    _normalize_competition_slugs,
    get_default_competition,
)

__all__ = [
    # Common
    "SortBy",
    "ScoreDirection",
    "COMPETITION_SLUG_PATTERN",
    "_normalize_competition_slugs",
    "SetActiveCompetitionRequest",
    "ActiveCompetitionInfo",
    # Kernels
    "KernelSummary",
    "ScoredKernel",
    "VersionInfo",
    "VersionScoreList",
    "ArchiveResult",
    "ArchiveEntry",
    "ArchiverConfig",
    "KernelListRequest",
    "ArchiveRequest",
    "EnrichRequest",
    "CompetitionInfo",
    "EnteredCompetition",
    # Auto Archive
    "AutoArchiveConfig",
    "AutoArchiveItemResult",
    "AutoArchiveStatus",
    "AutoArchiveRunLog",
    "AutoArchiveCheckedItem",
    "AutoArchiveRunDetail",
    "AutoArchiveSnapshot",
    # Notifications
    "NotificationConfig",
    "NotificationConfigUpdate",
    "NotificationConfigView",
    "NotificationStatus",
    "NotificationSnapshot",
    "NotificationChannelResult",
    "NotificationTestResult",
    # Submissions
    "CompetitionSubmission",
    "SubmissionMonitorConfig",
    "SubmissionScoreEvent",
    "SubmissionMonitorItem",
    "SubmissionMonitorStatus",
    "SubmissionMonitorRunLog",
    "SubmissionMonitorRunDetail",
    "SubmissionMonitorSnapshot",
    # Simulation
    "SimulationEpisodeAgent",
    "SimulationEpisode",
    "SimulationRatingPoint",
    "SimulationAgentStats",
    "SimulationMedalThresholds",
    "SimulationHistoryPoint",
    "SimulationMonitorConfig",
    "SimulationClawbotStatus",
    "SimulationClawbotTestCandidate",
    "SimulationClawbotTestResult",
    "SimulationMonitorStatus",
    "SimulationMonitorRunLog",
    "SimulationMonitorRunDetail",
    "SimulationEpisodePageResponse",
    "SimulationMonitorSnapshot",
]
